### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by alonsoir** [piomin/sample-spring-microservices-transactions#1]
Hello Piotr, I have tried to compile the project, but I find several problems. The first is solvable, it refers to an accont-service project, something that is easy to solve because the project you are referring to is account-service. Modify the pom.xml in the root of the project and put it to compile again.

[first problem](https://pastebin.com/u6j3pkJU)

The second problem is [this](https://pastebin.com/frGCb03A)

[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.3.1.RELEASE:repackage (repackage) on project product-service: Execution repackage of goal org.springframework.boot:spring-boot-maven-plugin:2.3.1.RELEASE:repackage failed: **Unable to find main class** -> [Help 1]

Since it is a kotlin project and I don't know about kotlin yet, I admit it, it may compile with a different phase of install, but I can't compile the project. Can you help me?

Thank you

**Comment by piomin** [comment]
Fixed.

[INFO] Reactor Summary for sample-spring-microservices-transactions 1.0-SNAPSHOT:
[INFO] 
[INFO] sample-spring-microservices-transactions ........... SUCCESS [  0.537 s]
[INFO] transaction-server ................................. SUCCESS [ 16.719 s]
[INFO] account-service .................................... SUCCESS [  5.125 s]
[INFO] product-service .................................... SUCCESS [  3.881 s]
[INFO] order-service ...................................... SUCCESS [  5.304 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.962 s
[INFO] Finished at: 2020-06-19T23:22:56+02:00
[INFO] ------------------------------------------------------------------------
