### ISSUE TITLE
Avoiding dirty reads/writes

### ISSUE THREAD

**Issue by gituserjava** [piomin/sample-spring-microservices-transactions#11]
While one transaction is in progress if another transaction reads the data how are you handling it?

For example, let's assume in transaction # 1, Order service first writes an order (order # 123) and moves to product service. At this point some other transaction/request (# 2) is trying get count of orders which includes # 123 also in it's count. After this point, if for some reason # 1 is rolled back, the count that is retrieved by # 2 is invalid. 

Can this framework handle such situations? Basically I am asking if this framework supports various countermeasures that are required for distributed transactions?

Please let me know. Thanks!

**Comment by piomin** [comment]
fixed
