### ISSUE TITLE
Error when running account service

### ISSUE THREAD

**Issue by alonsoir** [piomin/sample-spring-microservices-transactions#2]
Hi Piotr, i am following README instrucctions, when I started forth step, account-service, I got [this](https://pastebin.com/4b8fDF7E):

Caused by: java.net.UnknownHostException: postgresql

It looks like I have to run postgresql server. Could you add the instructions to have the postgres server working as you thought the project?

**Comment by piomin** [comment]
I have added such a step in readme documentation. I have also changed addresses to Postgres and Rabbit to localhost in application.yml
