### ISSUE TITLE
Exception, or warning with Order Service when starting from scratch.

### ISSUE THREAD

**Issue by alonsoir** [piomin/sample-spring-microservices-transactions#5]
Hi Piotr, First of all, thank you very much for your patience and I hope you do not mind my feedback on this project. I have reached the point of lifting the Order Service and when I lift it with the spring-boot: run phase, I get this [exception](https://pastebin.com/ZjuyWT2m).

It is not terminal, tomcat does not fail when the exception occurs, but there it is.

My environment is a macbook pro, this is my java and maven version.

Last login: Mon Jun 22 12:27:40 on ttys005
aironman @ MacBook-Pro-de-Alonso order-service% fish
Welcome to fish, the friendly interactive shell
aironman @ MacBook-Pro-de-Alonso ~ / g / s / order-service (master)> java -version
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment (build 14 + 36-1461)
OpenJDK 64-Bit Server VM (build 14 + 36-1461, mixed mode, sharing)

aironman @ MacBook-Pro-de-Alonso ~ / g / s / order-service (master)> mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 13.0.2, vendor: N / A, runtime: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.5", arch: "x86_64", family: "mac"
aironman @ MacBook-Pro-de-Alonso ~ / g / s / order-service (master)>

Now I realize that maven is using a different version of the jvm, but I don't think the problem is that. Seems a problem with the postgres library version along with the postgres server version.

**Comment by piomin** [comment]
Thanks  for your patience, since I have tested it on different project than this one, and that's some errors in this repo. I fixed it.
