### ISSUE TITLE
How can I add test data to the services?

### ISSUE THREAD

**Issue by alonsoir** [piomin/sample-spring-microservices-transactions#6]
You mentioned about to add some test data to account and product services, but how can I do it? There is not any test classes, using curl? Please, could you provide some examples? thank you.

**Comment by piomin** [comment]
I still didn't add any tests. You can use curl. Both `account-service` and `product-service` are starting on dynamic ports, so if want have them static you should set, for example server.port=9000.
```
$ curl -X POST http://localhost:<PORT>/accounts -H "Content-Type: application/json" -d "{\"customerId\":1, \"balance\":0}"
$ curl -X POST http://localhost:<PORT>/products -H "Content-Type: application/json" -d "{\"name\":\"Test\",\"count\":100, \"price\":1000}"
$ curl http://localhost:8080/orders -H "Content-Type: application/json" -d "{\"productId\":1, \"count\":10, \"customerId\":1}
```

**Comment by alonsoir** [comment]
Thank you so much for your patience. I really appreciate it.
