### ISSUE TITLE
testing Order service 

### ISSUE THREAD

**Issue by alonsoir** [piomin/sample-spring-microservices-transactions#7]
Hi Piotr, I have found this [problem](https://pastebin.com/U5uD78KT) when running curl command in order to get some orders.

I used these curl [commands](https://pastebin.com/P0juCM5k) in order to test Order Service.

It looks like that error happens in this class: pl.piomin.samples.account.listener.AccountTransactionListener, maybe, because stack trace shows something related to "transaction-server", and there are two methods, handleAfterRollback and handleAfterCompletion with this hardcoded name. Maybe in the real world with a DNS up and running, with the ip:port  of transaction server previously launched, there would not be any problem. I think that if I change my /etc/resolv.conf file with proper data, it should work. What do you think?

This is the [output](https://pastebin.com/58MZdzAA) of the running transaction-server process.

This is the output of my actual /etc/resolv.conf

aironman@MacBook-Pro-de-Alonso ~/g/s/order-service (master)> cat /etc/resolv.conf 
nameserver 80.58.61.254
nameserver 80.58.61.250

I think that if I add the next line to resolv.conf, it should do the job:

transaction-server 192.168.1.34:8888

In a real project, we should have this url in a properties file or something like that.

**Comment by piomin** [comment]
Did you run discovery server ?

**Comment by alonsoir** [comment]
Yes, this is an actual [output](https://pastebin.com/VGf3Rsi6).

by the way, ... it means this message:

2020-06-22 16:21:41.552  INFO 10106 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 

Please, consider change this message! :) there are a lot of these messages in a few hours...

**Comment by piomin** [comment]
It seems there are some problems with heartbeats on discovery. What's this address 192.168.1.34? It the same as localhost?

**2020-06-22 13:28:58.815  INFO 10106 --- [nio-8761-exec-8] c.n.e.registry.AbstractInstanceRegistry  : Cancelled instance ORDER-SERVICE/192.168.1.34:order-service (replication=false)
2020-06-22 13:28:59.322  WARN 10106 --- [io-8761-exec-10] c.n.e.registry.AbstractInstanceRegistry  : DS: Registry: cancel failed because Lease is not registered for: ORDER-SERVICE/192.168.1.34:order-service**
2020-06-22 13:28:59.322  INFO 10106 --- [io-8761-exec-10] c.n.eureka.resources.InstanceResource    : Not Found (Cancel): ORDER-SERVICE - 192.168.1.34:order-service
2020-06-22 13:28:59.322  WARN 10106 --- [get_localhost-1] c.n.eureka.cluster.ReplicationTask       : The replication of task ORDER-SERVICE/192.168.1.34:order-service:Cancel@localhost failed with response code 404
2020-06-22 13:28:59.322  WARN 10106 --- [get_localhost-1] c.netflix.eureka.cluster.PeerEurekaNode  : ORDER-SERVICE/192.168.1.34:order-service:Cancel@localhost: missing entry.

**Comment by alonsoir** [comment]
Hi Piotr, I am checking the orderly execution of all processes in case something has escaped me.
I have raised the discovery service, eureka, then the transaction service. I have stopped there. I go to localhost: 8761 to see what eureka says. I am attaching a screenshot of that time. 

<img width="1680" alt="Captura de pantalla 2020-06-23 a las 12 25 25" src="https://user-images.githubusercontent.com/2405946/85393031-a34b8980-b54c-11ea-8342-9b2654126db7.png">

Then, if I go to http://192.168.1.34:8888/actuator/info
I got this:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Jun 23 12:21:19 CEST 2020
There was an unexpected error (type=Not Found, status=404).

It seems normal, no error page from transaction-server.

Now, if I want to run next service, account-service, I got this:

2020-06-23 12:27:50.947  INFO 12929 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_ACCOUNT-SERVICE/192.168.1.34:account-service:0 - registration status: 204

The same ip than transaction-server! eureka is assigning the same assigned ip before to transaction-server to account-service! I suspect that if I run the next services, eureka is going to do the same...

Yes, eureka is assigning the same ip to every new instance. that's the problem.

2020-06-23 12:29:41.124  INFO 12958 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_PRODUCT-SERVICE/192.168.1.34:product-service:0: registering service...

2020-06-23 12:30:29.407  INFO 12986 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_ORDER-SERVICE/192.168.1.34:order-service - registration status: 204

**Comment by alonsoir** [comment]
I am noticing another bug since this morning. I'm trying to run all processes in order, well, when I try to run account-service and product-service processes, I see an [exception](https://pastebin.com/dtr44ErH) in both.

I am using this [script](https://pastebin.com/ZHssiSY5) in order to test it, if you want to use. Please, change the folder.

**Comment by piomin** [comment]
Two things. Actuator has not been added to the applications, so `/info` endpoint was not available - now I added it. I fixed problem with RabbitMQ queue, and I tested it now. Both account-service, and product-service are starting succesfully and creating queues trx-events-accounts and trx-events-product which are bound to topic exchange trx-events. 
However, in comparison with your test my services are registering using localhost. It's normal than it is always the same hostname - the difference is in ports. My inter-communication is via localhost, your is by IP 192.168.1.34. So I'm not if it would work succesfully on your test.

**Comment by alonsoir** [comment]
Thank you Piotr, I will try it right now, first of all, thank you very much for the effort and I hope I have not bothered you for the feedback I have provided. I think it is good for all of us that we have followed this attitude of testing, correcting, retesting. It is above all, the scientific way of dealing with this type of situation.

I will modify the script to work with the new build.

**Comment by alonsoir** [comment]
Ok, Piotr, is you said before, now, services are up and running. I am attaching the screenshot.
<img width="1680" alt="para piotr" src="https://user-images.githubusercontent.com/2405946/85535727-be80cc80-b612-11ea-8a35-bd098df6cb0b.png">

Now, I am going to add data to the services. Ok, accounts and products curl commands are successful, but, when I run order-service curl command, I see this [stacktrace](https://pastebin.com/ai94xias):

java.net.UnknownHostException: transaction-server: nodename nor servname provided, or not known

This is actual output from Eureka:
TRANSACTION-SERVER | n/a (1) | (1) | UP (1) - 192.168.1.34:transaction-server:8888
-- | -- | -- | --

I have tried with 

http://192.168.1.34:8888/transactions
returns method not allowed, status 405
