### ISSUE TITLE
Reopening Testing Order service 

### ISSUE THREAD

**Issue by alonsoir** [piomin/sample-spring-microservices-transactions#8]
Hi Piotr, i am reopening this [issue](https://github.com/piomin/sample-spring-microservices-transactions/issues/7).

**Comment by piomin** [comment]
Because there is no such method there :) I added also method for finding all existing transactions now

**Comment by alonsoir** [comment]
hi Piotr, do you think adding that new method will fix the exception that occurs when I invoke the service with the CURL command?
The exception is this:

java.net.UnknownHostException: transaction-server: nodename nor servname provided, or not known

I'll test it tomorrow morning. Thank you very much for your effort.

**Comment by piomin** [comment]
No, but you you wrote you have the following exception:
I have tried with

http://192.168.1.34:8888/transactions
returns method not allowed, status 405

You can't call http://transaction-server/... using curl.

**Comment by alonsoir** [comment]
Hi Piotr, i am afraid it doesn't work.

I am not invoking transaction-server using curl. I am using curl in order to test order-service, like this:

curl http://192.168.1.34:8080/orders -H "Content-Type: application/json" -d "{\"productId\":1, \"count\":10, \"customerId\":1}"
which returns this exception:

java.net.UnknownHostException: transaction-server: nodename nor servname provided, or not known

I have dropped the complete folder, download it again, compiled, and same error, same exception.

Could you share what you have different from me in order that order-service works in your localhost machine?

<img width="1680" alt="Captura de pantalla 2020-06-25 a las 13 16 25" src="https://user-images.githubusercontent.com/2405946/85710079-2d7b2580-b6e6-11ea-99e5-5e9c339fb417.png">
